CREATE TABLE ROLE (
  ROLE_ID INT NOT NULL,
  DEPARTMENT_ID INT NOT NULL,
  USER_GROUP_ID INT NOT NULL,
  ROLE_NAME CHAR(128),
  ADMIN_FLG CHAR(1),
  PRIMARY KEY(DEPARTMENT_ID, USER_GROUP_ID, ROLE_ID)
);
