CREATE TABLE USER (
  USER_ID INT NOT NULL,
  USER_NAME CHAR(128),
  ENCRPTION_FLG CHAR(1) NOT NULL,
  PASSWORD CHAR(40),
  DEPARTMENT_ID INT,
  USER_GROUP_ID INT,
  ROLE_ID INT,
  PRIMARY KEY (USER_ID)
);
