INSERT INTO DEPARTMENT VALUES(1, 'SYSTAM_DEPARTMENT');
INSERT INTO USER_GROUP VALUES(1, 1, 'SYSTEM_GROUP');
INSERT INTO ROLE VALUES(1, 1, 1, 'SYSTEM_ROLE', '1');
INSERT INTO USER VALUES(1, 'SYSTEM_USER', '0', 'admin', 1, 1, 1);